import uniq from 'lodash/uniq'
import Head from 'next/head'
import styled from 'styled-components'

import { Header, Menu, Characters } from '../../components'
import apolloClient from '../../lib/apollo'
import { EPISODES_IDS_QUERY, MENU_QUERY } from '../../lib/queries'
import { LOCATION_ROUTES_QUERY, EPISODE_BY_ID_QUERY } from '../../lib/queries'
import type { Location, Character, Episode, Context } from '../../lib/types'

const PageWidth = styled.div`
  margin: 0 auto;
  max-width: 1200px;
  padding: 0 4px;
  color: ${(p) => p.theme.colors.primary};
`

const Content = styled.div`
  display: flex;
`

export async function getStaticPaths() {
  const { data } = await apolloClient.query({
    query: EPISODES_IDS_QUERY,
  })
  const episodesIds = data.episodes.results.map((episode: Episode) => episode.id)
  const paths = episodesIds.map((epsiodeId: string) => {
    return {
      params: {
        id: epsiodeId,
      },
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }: Context) {
  const { id: episodeId } = params

  const { data: MenuData } = await apolloClient.query({
    query: MENU_QUERY,
  })

  const { data } = await apolloClient.query({
    query: EPISODE_BY_ID_QUERY,
    variables: { id: episodeId },
  })

  const { episodes, locations } = MenuData
  const { characters } = data.episode

  return {
    props: {
      episodes: episodes.results,
      characters: characters,
      locations: locations.results,
    },
  }
}

type Props = {
  characters: Character[]
  episodes: Episode[]
  locations: Location[]
}

function CharactersByLocation(props: Props) {
  const { episodes, locations, characters } = props

  return (
    <>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWidth>
        <Header>Rick and Morty API - Dimension</Header>
        <Content>
          <Menu episodes={episodes} locations={locations} characters={characters} />
          <Characters characters={characters} />
        </Content>
      </PageWidth>
    </>
  )
}

export default CharactersByLocation
