import { gql, useQuery } from '@apollo/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styled from 'styled-components'

import { Header, Menu, Characters } from '../components'
import apolloClient from '../lib/apollo'
import { HOMEPAGE_QUERY } from '../lib/queries'
import { Character, Episode } from '../lib/types'

const PageWidth = styled.div`
  margin: 0 auto;
  max-width: 1200px;
  padding: 0 4px;
  color: ${(p) => p.theme.colors.primary};
`

const Content = styled.div`
  display: flex;
`

export async function getStaticProps() {
  const { data } = await apolloClient.query({
    query: HOMEPAGE_QUERY,
  })

  const { episodes, characters, locations } = data

  return {
    props: {
      episodes: episodes.results,
      characters: characters.results,
      locations: locations.results,
    },
  }
}

type Props = {
  characters: Character[]
  episodes: Episode[]
  locations: Location[]
}

function Home(props: Props) {
  const { episodes, locations } = props
  const [characters, setCharacters] = useState(props.characters)

  const { loading, data, error } = useQuery(HOMEPAGE_QUERY, { variables: { year: 2019 } })

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error {error.message}</p>

  //Apollo useQuery gebruiken
  // filters + query obv category
  // useQUery skip: if filters = null
  // useState met characters als init state

  function onMenuItemClick(category, variable) {
    console.log({ category })

    console.log({ variable })
  }

  return (
    <>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWidth>
        <Header>Rick and Morty API</Header>
        <Content>
          <Menu
            onClick={onMenuItemClick}
            episodes={episodes}
            locations={locations}
            characters={characters}
          />
          <Characters characters={characters} />
        </Content>
      </PageWidth>
    </>
  )
}

export default Home
