import { gql, useQuery } from '@apollo/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Menu } from '../components'
import styles from '../styles/Home.module.css'

const EXCHANGE_RATES = gql`
  query {
    characters {
      info {
        count
      }
      results {
        id
        name
        status
        species
        type
        gender
        origin {
          id
          name
          type
          dimension
          created
        }
        location {
          id
          name
          type
          dimension
          created
        }
        image
        episode {
          id
          name
          air_date
          created
        }
        created
      }
    }
    episodesByIds(ids: [1, 2]) {
      id
    }
  }
`

const Home: NextPage = () => {
  const { loading, error, data } = useQuery(EXCHANGE_RATES)

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error {error.message}</p>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      {data.characters.results.map((character) => (
        <>
          <Image alt={character.name} src={character.image} width="40" height="40" />
          <p>{character.name}</p>
        </>
      ))}
    </>
  )
}

export default Home
