import uniq from 'lodash/uniq'
import Head from 'next/head'
import styled from 'styled-components'

import { Header, Menu, Characters } from '../../components'
import apolloClient from '../../lib/apollo'
import { MENU_QUERY } from '../../lib/queries'
import { LOCATION_ROUTES_QUERY, LOCATION_BY_ID_QUERY } from '../../lib/queries'
import type { Location, Character, Episode, Context } from '../../lib/types'

const PageWidth = styled.div`
  margin: 0 auto;
  max-width: 1200px;
  padding: 0 4px;
  color: ${(p) => p.theme.colors.primary};
`

const Content = styled.div`
  display: flex;
`

export async function getStaticPaths() {
  const { data } = await apolloClient.query({
    query: LOCATION_ROUTES_QUERY,
  })
  const locationIds = data.locations.results.map((location: Location) => location.id)
  const paths = locationIds.map((locationId: string) => {
    return {
      params: {
        id: locationId,
      },
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }: Context) {
  const { id: locationId } = params

  const { data: MenuData } = await apolloClient.query({
    query: MENU_QUERY,
  })

  console.log({ locationId })
  const { data } = await apolloClient.query({
    query: LOCATION_BY_ID_QUERY,
    variables: { id: locationId },
  })

  const { episodes, locations } = MenuData
  const { residents } = data.location

  return {
    props: {
      episodes: episodes.results,
      characters: residents,
      locations: locations.results,
    },
  }
}

type Props = {
  characters: Character[]
  episodes: Episode[]
  locations: Location[]
}

function CharactersByLocation(props: Props) {
  const { episodes, locations, characters } = props

  return (
    <>
      <Head>
        <title>Rick and Morty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWidth>
        <Header>Rick and Morty API - Dimension</Header>
        <Content>
          <Menu episodes={episodes} locations={locations} characters={characters} />
          <Characters characters={characters} />
        </Content>
      </PageWidth>
    </>
  )
}

export default CharactersByLocation
